import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Remove Navbar import
// import Navbar from "@/components/Navbar";

// Initialize Inter font
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// Remove Geist font imports and variables
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// 
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Remove default metadata
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${inter.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
